### ISSUE TITLE
Limit on the number of APM services listed in Optimizer

### ISSUE THREAD

**Issue by sujitdesiraju-1420** [newrelic/nr1-apdex-optimizer#11]
Hi,

Thank you very much for this App. It is very useful and have started using the App to perform Apdex analysis for our Apps. I have observed that this App displays only around 150 APM services under an account. We have some accounts with services more than that number. Is there a way to display all the services or search for the service for which want to perform Apdex Analysis?

**Comment by reebr1234** [comment]
I too would like to see more applications and/or search for them.  We have thousands under 1 account, so without this upgrade, the Optimizer is not very useful.

**Comment by reebr1234** [comment]
I downloaded the new version and I now see all my applications.  However, when I click on the time picker to change to something greater than 30 minutes, it seems to just seems to refresh a new 30 minutes.   We have over 4500 applications, so this may be part of the problem.  Any suggestions?
