### ISSUE TITLE
Unable to select account running local and EU datacenter

### ISSUE THREAD

**Issue by oskbo** [newrelic/nr1-apdex-optimizer#19]
The select account dropdown is empty. 

I followed the guide for running the newrpack on Windows. Settings upp n1 cli and added API key from EU datacenter.

![image](https://user-images.githubusercontent.com/1083828/107149724-89837900-695a-11eb-8761-33716cf024a3.png)

**Comment by crshanks** [comment]
Hi @oskbo - It seems that I need to update the readme. If your account is in the EU region and the API key is associated with that account you need to navigate to:

- https://one.eu.newrelic.com/?nerdpacks=local if serving locally
- https://one.eu.newrelic.com if the application is published and the account subscribed.
